version: '3.3'

services:

  axon-server:
    image: axoniq/axonserver:${AXON_VERSION:-latest}
    ports:
      - 8024:8024
    volumes:
      - axon-data:/data
      - axon-eventdata:/eventdata
      - ./config:/config

  mongo:
    image: mongo:${MONGO_VERSION:-latest}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: art_user
      MYSQL_PASSWORD: art_password
      MYSQL_DATABASE: bank_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

  user-cmd-api:
    image: artarkatesoft/art-campbell-cqrs-user-cmd-api:${SERVICE_VERSION:-latest}
    environment:
      "spring.data.mongodb.host": mongo
      "axon.axonserver.servers": axon-server
    depends_on:
      mongo:
        condition: service_healthy

  user-query-api:
    image: artarkatesoft/art-campbell-cqrs-user-query-api:${SERVICE_VERSION:-latest}
    environment:
      "spring.data.mongodb.host": mongo
      "axon.axonserver.servers": axon-server
    depends_on:
      mongo:
        condition: service_healthy

  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  oauth20-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./../../user-management/user-storage-provider/target/remote-user-storage-provider.jar:/opt/jboss/keycloak/standalone/deployments/remote-user-storage-provider.jar

  bankaccount-cmd-api:
    image: artarkatesoft/art-campbell-cqrs-bankaccount-cmd-api:${SERVICE_VERSION:-latest}
    depends_on:
      mongo:
        condition: service_healthy

  bankaccount-query-api:
    image: artarkatesoft/art-campbell-cqrs-bankaccount-query-api:${SERVICE_VERSION:-latest}
    restart: on-failure:5
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy

  api-gateway:
    image: artarkatesoft/art-campbell-cqrs-api-gateway:${SERVICE_VERSION:-latest}
    ports:
      - 2000:8080
    restart: on-failure:5
    depends_on:
      user-cmd-api:
        condition: service_healthy
      user-query-api:
        condition: service_healthy
      bankaccount-cmd-api:
        condition: service_healthy
      bankaccount-query-api:
        condition: service_healthy
      oauth20-server:
        condition: service_healthy

volumes:
  axon-data:
  axon-eventdata:
  mongo-data:
  mysql-data:
  postgres_data:




