# spring
server:
  port: 2000

logging.level:
  net.shyshkin: debug


# routes
app.routes.uri:
  user-cmd-api: http://user-cmd-api:8080
  user-query-api: http://user-query-api:8080
  bankaccount-cmd-api: http://bankaccount-cmd-api:8080
  bankaccount-query-api: http://bankaccount-query-api:8080
  oauth20-server: http://oauth20-server:8080

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi
          uri: ${app.routes.uri.user-cmd-api}/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**
            - Method=POST,PUT,DELETE
        - id: userQueryApi
          uri: ${app.routes.uri.user-query-api}/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**
            - Method=GET
        - id: bankAccountCmdApi
          uri: ${app.routes.uri.bankaccount-cmd-api}/api/v1/accounts/**
          predicates:
            - Path=/api/v1/accounts/**
            - Method=POST,PUT,DELETE
        - id: bankAccountQueryApi
          uri: ${app.routes.uri.bankaccount-query-api}/api/v1/accounts/**
          predicates:
            - Path=/api/v1/accounts/**
            - Method=GET
        - id: oauth20-server
          uri: ${app.routes.uri.oauth20-server}/auth/**
          predicates:
            - Path=/auth/**

---
spring:
  config:
    activate:
      on-profile: local

app.routes.uri:
  user-cmd-api: http://localhost:8091
  user-query-api: http://localhost:8092
  bankaccount-cmd-api: http://localhost:9091
  bankaccount-query-api: http://localhost:9092
  oauth20-server: http://localhost:8080