# spring
server:
  port: 9091
spring.application.name: bank-account-command-api
logging.level:
  net.shyshkin: debug

# mongodb
spring.data.mongodb:
  host: mongo
  port: 27017
  database: bank_account_db

#axon
axon.axonserver.servers: axon-server

# security
app.oauth.uri: http://oauth20-server:8080
#spring.security.oauth2.resourceserver.jwt.issuer-uri: ${app.oauth.uri}/auth/realms/katarinazart
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: ${app.oauth.uri}/auth/realms/katarinazart/protocol/openid-connect/certs
---
spring:
  config:
    activate:
      on-profile: local

app.oauth.uri: http://localhost:8080

#mongodb
spring.data.mongodb:
  host: localhost

#axon
axon.axonserver.servers: localhost
