# spring
server:
  port: 9092
spring.application.name: bank-account-query-api
logging.level:
  net.shyshkin: debug

# mongodb
spring.data.mongodb:
  host: localhost
  port: 27017
  database: bank_account_db

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:23306/bank_db
    username: art_user
    password: art_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update


# security
security.oauth2.resource.jwt.key-value: springbankSigningKey
